resources:
  containers:
    - container: test
      image: wso2/choreo-connect-router:0.9.0

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: foo
    services:
      test: test
    variables:
      - name: REPO_PATH
        value: '$(Agent.BuildDirectory)/pipelines-java'
    # container: test
    steps:
      # - task: Docker@2
      #   inputs:
      #     containerRegistry: 'DockerHub-Renuka'
      #     repository: 'apioperator/pipline-test'
      #     command: 'build'
      #     Dockerfile: '**/Dockerfile'
      - script: |
          set -e
          wget https://github.com/wso2/product-microgateway/releases/download/v0.9.0/choreo-connect-0.9.0.zip \
          -O $(Agent.TempDirectory)/choreo-connect-0.9.0.zip
          unzip -q $(Agent.TempDirectory)/choreo-connect-0.9.0.zip -d $(Agent.TempDirectory)
          cd $(Agent.TempDirectory)/choreo-connect-0.9.0/docker-compose/choreo-connect-with-apim
          docker-compose up router adapter enforcer
        displayName: "Deploy"
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
